---
# tasks file for ansible-role-hibenchi/
## maven install and configure 
- stat: path={{ maven_home }}
  register: maven_installed
  tags:
    - m1
- include: install.yml
  when: not maven_installed.stat.exists
  tags:
    - m2

- include: configure.yml
  #when: not maven_installed.stat.exists
  tags:
    - m3


